### ISSUE TITLE
Crashes when query duration or query position is called

### ISSUE THREAD

**Issue by bsceran** [gstreamer-java/gstreamer-java#149]
When I try to invoke the following queries, my application crashes;
pipeline.queryDuration(TimeUnit.SECONDS);
position = pipeline.queryPosition(TimeUnit.SECONDS);

This does not happen when I use the previous version before the fix "backport fixes from gst1-java-core".
Please see my attached log file.

[hs_err_pid2232.log.txt](https://github.com/gstreamer-java/gstreamer-java/files/168790/hs_err_pid2232.log.txt)
[feedback.txt](https://github.com/gstreamer-java/gstreamer-java/files/168791/feedback.txt)

**Comment by neilcsmith-net** [comment]
Yes, @lfarkas - those functions changed API in 1.x.  I hadn't realised until I got notification of this email that you were backporting fixes.  Need to be very careful of anything that touches native code there - there are so many quirky little changes like that (Format[] to Format) because the underlying API switched from a pointer.

**Comment by lfarkas** [comment]
i hope it's fix it.
